\begin{SubTitle}
(((phone_number)))
\,\SubBulletSymbol\,
\href{mailto:(((email)))}
{(((email)))}
\,\SubBulletSymbol\,
{(((location)))}
\par
\color{blue}
\href{\CVWebpage}
{(((website)))}
\color{black}
\,\SubBulletSymbol\,
\color{blue}
\href{(((github_url)))}
{(((github_pretty_url)))}
\color{black}
\,\SubBulletSymbol\,
\color{blue}
\href{(((linkedin_url)))}
{(((linkedin_pretty_url)))}
\color{black}
\end{SubTitle}
