// The look of the PDF resume, ported from simpleresumecv.cls
// <https://github.com/zachscrivena/simple-resume-cv>.
//
// The document itself is generated by src/resume.rs from the resume markdown
// and fed into resume.typ; everything here is layout.

// LaTeX sets lines a fixed distance apart; Typst sets a gap between them.
// A line of Tinos occupies 0.655em between those two measures, so this is
// what `\baselineskip` of `lead` costs in Typst.
#let leading(size, lead) = lead - 0.655 * size

// TeX keeps its lines `\baselineskip` apart across a paragraph break as well
// as within one, so blocks are spaced by the same amount they lead by. That
// is `\parskip` of zero, not a gap of zero.
#let lines(size, lead) = (leading: leading(size, lead), spacing: leading(size, lead))

#let body-size = 12pt
#let body-lead = 14.5pt // \baselineskip at 12pt
#let detail-size = 11pt
#let detail-lead = 13.2pt
#let body-gap = leading(body-size, body-lead)

// The extra space between the items of one section, and between sections.
// Weak, so that it absorbs the ordinary spacing rather than adding to it.
#let gap = v(body-gap + 0.45mm, weak: true)
#let section-gap = v(body-gap + 0.90 * body-lead, weak: true)

// The marker of a bullet, sized and raised as the class draws it.
#let marker(size, indent, sym) = box(
  h(indent) + text(size: size, baseline: -0.17em, sym) + h(1.5mm),
)

// A bullet whose wrapped lines hang clear of the marker, the way the class
// reshapes the paragraph around one. The indent has to be given to `par`
// directly: a `set` rule for it does not reach the paragraph from in here.
#let hanging(mark, body) = block(
  width: 100%,
  context par(hanging-indent: measure(mark).width, mark + body),
)

// The role of a job, or the degree of a school.
#let bullet(body) = hanging(marker(6.5pt, 1.5mm, "\u{25A0}"), body)

// A line of detail under one of those.
#let sub-bullet(body) = hanging(marker(6pt, 5.6mm, "\u{25CF}"), body)

// The separator between the parts of the subtitle.
#let sub-sep = text(size: 6pt, baseline: -0.17em, "\u{25CF}")

// A link spelled out in full, as the subtitle and the projects show them.
#let shown-link(url, label) = text(fill: rgb("#1f4e8c"), link(url, label))

// An organisation and its places, with the dates on the right — or, for a
// project, its link there instead.
#let entry(head, aside: none, role: none, detail: none) = {
  block(width: 100%, {
    head
    if aside != none {
      h(1fr)
      aside
    }
  })
  if role != none {
    gap
    bullet(role)
  }
  if detail != none {
    gap
    block({
      set text(size: detail-size)
      set par(..lines(detail-size, detail-lead))
      detail
    })
  }
  gap
}

#let section(title) = block(width: 100%, {
  set par(..lines(15pt, 18pt))
  align(center, text(size: 15pt, weight: "bold", upper(title)))
})

// The monogram sits in the top-left corner, its top on the cap height of the
// name (where the block starts), and is
// placed so the name stays centred on the page.
#let name(body) = block(width: 100%, {
  set par(..lines(20pt, 24pt))
  place(top + left, image("/logo.svg", height: 0.38in))
  align(center, text(size: 20pt, weight: "bold", body))
})

#let subtitle(body) = {
  v(body-gap + 0.25 * body-lead, weak: true)
  block(width: 100%, {
    set text(size: detail-size)
    set par(..lines(detail-size, detail-lead))
    align(center, body)
  })
  v(body-gap + body-lead, weak: true)
}

#let resume(author: "", title: "", doc) = {
  set document(author: author, title: title)
  set page(
    paper: "us-letter",
    margin: (left: 0.70in, right: 0.70in, top: 0.60in, bottom: 0.45in),
  )
  set text(font: "Tinos", size: body-size, hyphenate: false)
  set par(..lines(body-size, body-lead), justify: true)
  doc
}
